### PR TITLE
fix(Select): add value prop, fix onSelect function

### LINKED ISSUE #107: (Select): button/input only displays value of selected item
Need to be more customizable about what is show as the selected item. Several updates that need to be done:
 - Update List to pass up both value and label in onSelect function
 - Update selected in state to be objects with Label and Value props

### PR DESCRIPTION
**Pull request by daanishnasir**
Resolves #107

### CODE REVIEW

File: src/docs/containers/Playground/insertExampleHere.js [hunk 1]
```diff
@@ -9,7 +10,14 @@ export default class PlaygroundComponent extends React.Component {
...
       <ErrorBoundary fallbackComponent={<ErrorContainer />}>
-        <div />
+
+        <div className="medium-6 columns">
+            <Select defaultValue='Select Item Here' >
+                <SelectOption value='ben' label='test1' />
+                <SelectOption value='dunit' label='test2' />
+                <SelectOption value='paul' label='test3' />
+            </Select>
+        </div>
```
Comment (bfbiggs) [inline src/docs/containers/Playground/insertExampleHere.js]: Remove these changes from the example file.

File: src/lib/SelectOption/index.js [hunk 2]
```diff
@@ -52,16 +58,17 @@ class SelectOption extends React.Component {
...
-        {separateChildren}
-      </ListItem>
+       <ListItem
+         className={`${(className && ` ${className}`) || ''}`}
+         id={id}
+         label={label}
+         title={title || label}
+         {...props}
+        >
+
```
Comment (bfbiggs) [inline src/lib/SelectOption/index.js]: Remove empty lines around child.

File: src/lib/SelectOption/index.js [hunk 3]
```diff
@@ -52,16 +58,17 @@ class SelectOption extends React.Component {
...
+            {separateChildren}
```
Comment (bfbiggs) [inline src/lib/SelectOption/index.js]: Remove extra tab.

File: src/lib/ListItem/index.js [hunk 4]
```diff
@@ -97,16 +97,22 @@ class ListItem extends React.Component {
   };
 
   handleClick = e => {
-    const { disabled, itemIndex, onClick, value } = this.props;
+    const {
+       disabled,
```
Comment (bfbiggs) [inline src/lib/ListItem/index.js]: Change tab to 2 spaces.

File: src/docs/containers/Playground/insertExampleHere.js [hunk 5]
```diff
@@ -1,6 +1,7 @@
 import React from 'react';
 import ErrorBoundary from '@collab-ui/react/ErrorBoundary';
 import ErrorContainer from '../ErrorContainer';
+import { Select, SelectOption } from '@collab-ui/react';
```
Comment (bfbiggs) [inline src/docs/containers/Playground/insertExampleHere.js]: Remove import of Selects.
